"""Hook Events - Standard lifecycle events for the Agent Runtime."""

# Session lifecycle
BEFORE_SESSION = "BEFORE_SESSION"
AFTER_SESSION = "AFTER_SESSION"

# Agent lifecycle
BEFORE_AGENT = "BEFORE_AGENT"
AFTER_AGENT = "AFTER_AGENT"

# Skill lifecycle
BEFORE_SKILL = "BEFORE_SKILL"
AFTER_SKILL = "AFTER_SKILL"

# LLM lifecycle
BEFORE_LLM = "BEFORE_LLM"
AFTER_LLM = "AFTER_LLM"

# Tool lifecycle
BEFORE_TOOL = "BEFORE_TOOL"
AFTER_TOOL = "AFTER_TOOL"

# Error handling
ON_ERROR = "ON_ERROR"
ON_RETRY = "ON_RETRY"

# Execution runtime events
BEFORE_EXECUTE_TASK = "BEFORE_EXECUTE_TASK"
AFTER_EXECUTE_TASK = "AFTER_EXECUTE_TASK"
ON_TASK_FAIL = "ON_TASK_FAIL"

# All standard events (for registration validation)
ALL_HOOK_EVENTS = [
    BEFORE_SESSION, AFTER_SESSION,
    BEFORE_AGENT, AFTER_AGENT,
    BEFORE_SKILL, AFTER_SKILL,
    BEFORE_LLM, AFTER_LLM,
    BEFORE_TOOL, AFTER_TOOL,
    ON_ERROR, ON_RETRY,
    BEFORE_EXECUTE_TASK, AFTER_EXECUTE_TASK, ON_TASK_FAIL,
]