"""Hook package."""
from runtime.v3.hook.manager import (
    HookManager,
    HookHandler,
    create_logging_hook,
    create_progress_hook,
    # Event type constants
    BEFORE_AGENT, AFTER_AGENT,
    BEFORE_CAPABILITY, AFTER_CAPABILITY,
    QUALITY_CHECK, QUALITY_PASSED, QUALITY_FAILED, QUALITY_ASK_USER,
    CHECKPOINT_SAVE, CHECKPOINT_RESTORE,
    HUMAN_REVIEW_REQUEST, HUMAN_FEEDBACK,
    WORLD_UPDATE,
    PROJECT_START, PROJECT_COMPLETE, PROJECT_RESUME, PROJECT_ERROR,
)

__all__ = [
    "HookManager",
    "HookHandler",
    "create_logging_hook",
    "create_progress_hook",
    "BEFORE_AGENT", "AFTER_AGENT",
    "BEFORE_CAPABILITY", "AFTER_CAPABILITY",
    "QUALITY_CHECK", "QUALITY_PASSED", "QUALITY_FAILED", "QUALITY_ASK_USER",
    "CHECKPOINT_SAVE", "CHECKPOINT_RESTORE",
    "HUMAN_REVIEW_REQUEST", "HUMAN_FEEDBACK",
    "WORLD_UPDATE",
    "PROJECT_START", "PROJECT_COMPLETE", "PROJECT_RESUME", "PROJECT_ERROR",
]