"""Planner Agent - Decomposes user requirements into executable task DAGs.

The Planner takes a high-level user request and breaks it down into
a structured execution plan.

V2.5: Simple rule-based decomposition
V3+: LLM-powered dynamic planning

Example:
    User: "Generate a 3-episode campus romance comic drama"
    Planner → {
        "episodes": 3,
        "scenes_per_episode": [8, 7, 9],
        "steps": ["script", "character", "storyboard", "image", "voice", "video"],
        "parallel_groups": {
            "image_voice": ["image", "voice"],  # Can run in parallel per scene
        },
        "total_scenes": 24,
        "estimated_duration": "15min"
    }
"""

import json
import logging
from dataclasses import dataclass, field
from typing import Any

from runtime.event_bus import EventBus, EventType, get_event_bus

logger = logging.getLogger(__name__)


@dataclass
class TaskNode:
    """A single task in the execution plan."""
    id: str
    name: str
    agent: str              # Which agent to use
    dependencies: list[str] = field(default_factory=list)
    input_keys: list[str] = field(default_factory=list)  # Blackboard keys needed
    output_keys: list[str] = field(default_factory=list)  # Blackboard keys produced
    parallel_group: str = ""  # Tasks in the same group can run in parallel
    metadata: dict = field(default_factory=dict)

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "name": self.name,
            "agent": self.agent,
            "dependencies": self.dependencies,
            "input_keys": self.input_keys,
            "output_keys": self.output_keys,
            "parallel_group": self.parallel_group,
            "metadata": self.metadata,
        }


@dataclass
class ExecutionPlan:
    """A complete execution plan generated by the Planner."""
    user_request: str
    genre: str
    tasks: list[TaskNode] = field(default_factory=list)
    metadata: dict = field(default_factory=dict)

    def get_task(self, task_id: str) -> TaskNode | None:
        for task in self.tasks:
            if task.id == task_id:
                return task
        return None

    def get_ready_tasks(self, completed: set[str]) -> list[TaskNode]:
        """Get tasks whose dependencies are all completed."""
        ready = []
        for task in self.tasks:
            if task.id in completed:
                continue
            if all(dep in completed for dep in task.dependencies):
                ready.append(task)
        return ready

    def get_parallel_groups(self) -> dict[str, list[TaskNode]]:
        """Group tasks by their parallel_group."""
        groups: dict[str, list[TaskNode]] = {}
        for task in self.tasks:
            group = task.parallel_group or task.id
            groups.setdefault(group, []).append(task)
        return groups

    def to_dict(self) -> dict:
        return {
            "user_request": self.user_request,
            "genre": self.genre,
            "tasks": [t.to_dict() for t in self.tasks],
            "metadata": self.metadata,
        }

    def get_linear_pipeline(self) -> list[str]:
        """Get the pipeline as a linear list of agent names.

        This is used by the WorkflowEngine in V1/V2 mode.
        """
        # Topological sort
        completed = set()
        pipeline = []
        max_iterations = len(self.tasks) + 1

        while len(completed) < len(self.tasks) and max_iterations > 0:
            ready = self.get_ready_tasks(completed)
            if not ready:
                break
            for task in ready:
                pipeline.append(task.agent)
                completed.add(task.id)
            max_iterations -= 1

        return pipeline


class PlannerAgent:
    """Decomposes user requirements into execution plans.

    V2.5: Rule-based planning for known task types (comic drama, etc.)
    V3+: LLM-powered dynamic planning for arbitrary workflows
    """

    # Known task types and their default pipeline
    KNOWN_PIPELINES = {
        "comic": ["script", "character", "storyboard", "image", "voice", "video"],
        "novel": ["script", "character", "chapter_outline", "text_generation"],
        "animation": ["script", "character", "storyboard", "image", "voice", "video"],
        "ad": ["script", "storyboard", "image", "voice", "video"],
        "movie": ["script", "character", "storyboard", "image", "voice", "video"],
    }

    def __init__(self, event_bus: EventBus | None = None):
        self.event_bus = event_bus or get_event_bus()

    async def plan(self, prompt: str, genre: str = "campus",
                    metadata: dict | None = None) -> ExecutionPlan:
        """Create an execution plan from a user request.

        Args:
            prompt: User's creative prompt
            genre: Story genre
            metadata: Additional constraints/options

        Returns:
            An ExecutionPlan ready for the WorkflowEngine
        """
        meta = metadata or {}

        # Determine task type
        task_type = meta.get("task_type", self._infer_task_type(genre, meta))
        pipeline = self.KNOWN_PIPELINES.get(task_type, self.KNOWN_PIPELINES["comic"])

        # Build task DAG
        tasks = self._build_task_dag(pipeline, prompt, genre, meta)

        plan = ExecutionPlan(
            user_request=prompt,
            genre=genre,
            tasks=tasks,
            metadata={
                "task_type": task_type,
                "pipeline": pipeline,
                **meta,
            },
        )

        logger.info("Planner created plan: %d tasks, type=%s, genre=%s",
                     len(tasks), task_type, genre)

        await self.event_bus.publish_event(
            EventType.PLAN_CREATED,
            data=plan.to_dict(),
            source="planner",
        )

        return plan

    def _infer_task_type(self, genre: str, metadata: dict) -> str:
        """Infer the task type from genre and metadata."""
        explicit = metadata.get("task_type")
        if explicit:
            return explicit

        # Map genre to task type
        genre_map = {
            "novel": "novel",
            "ad": "ad",
            "movie": "movie",
            "animation": "animation",
        }
        for key, value in genre_map.items():
            if key in genre.lower():
                return value

        return "comic"  # Default

    def _build_task_dag(self, pipeline: list[str], prompt: str,
                         genre: str, metadata: dict) -> list[TaskNode]:
        """Build a DAG of TaskNodes from a linear pipeline.

        V1/V2: Linear DAG (each step depends on the previous)
        V2.5+: Can introduce parallelism (e.g., image + voice per scene)
        """
        tasks = []
        prev_id = None

        # Define input/output keys for each step
        step_io = {
            "script": {
                "input_keys": ["prompt", "genre"],
                "output_keys": ["outline", "episodes", "characters"],
            },
            "character": {
                "input_keys": ["characters", "outline"],
                "output_keys": ["characters"],
            },
            "storyboard": {
                "input_keys": ["episodes", "characters"],
                "output_keys": ["storyboard", "scenes"],
            },
            "image": {
                "input_keys": ["storyboard", "characters"],
                "output_keys": ["images"],
            },
            "image_to_video": {
                "input_keys": ["images"],
                "output_keys": ["video_clips"],
            },
            "voice": {
                "input_keys": ["storyboard", "characters"],
                "output_keys": ["audios"],
            },
            "video": {
                "input_keys": ["images", "audios", "video_clips"],
                "output_keys": ["video_path"],
            },
        }

        for i, step in enumerate(pipeline):
            task_id = f"task_{i:03d}_{step}"
            io = step_io.get(step, {"input_keys": [], "output_keys": [step]})

            # Determine parallel group
            parallel_group = ""
            if step in ("image", "voice") and metadata.get("parallel_media"):
                parallel_group = "media_generation"

            task = TaskNode(
                id=task_id,
                name=f"Step {i+1}: {step}",
                agent=step,
                dependencies=[prev_id] if prev_id else [],
                input_keys=io["input_keys"],
                output_keys=io["output_keys"],
                parallel_group=parallel_group,
                metadata={"step_index": i},
            )
            tasks.append(task)
            prev_id = task_id

        return tasks

    def get_stats(self) -> dict:
        """Get Planner statistics."""
        return {
            "known_pipelines": list(self.KNOWN_PIPELINES.keys()),
        }